language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache

matrix:
    include:
        - php: hhvm
          env: COMPOSER_EXTRA="--prefer-lowest --prefer-stable"
        - php: 7.1.3
          env: COMPOSER_EXTRA="--prefer-lowest --prefer-stable"
    fast_finish: true

install:
    - composer --prefer-source $COMPOSER_EXTRA update

script:
    - vendor/bin/phpunit Tests/
